In [5]:
import numpy as np


In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [8]:
a[0]

1

In [9]:
a[1]

2

In [10]:
a[2]

3

In [11]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [12]:
import numpy as np
import time
import sys
l=range(1000)
l
print(sys.getsizeof(5)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)

14000
4000


In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1-a2

array([-3, -3, -3])

In [15]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1*a2

array([ 4, 10, 18])

In [16]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1/a2

array([0.25, 0.4 , 0.5 ])

In [17]:
#Single Dimensinal Array
a=np.array([1,2])
a

array([1, 2])

In [18]:
#1 Dimensinal Array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a=np.array( [1,2],[3,4])
a

TypeError: data type not understood

In [ ]:
import numpy as np

In [11]:
np.array([1,2],[3,4])


TypeError: data type not understood

In [12]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [13]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [17]:
a=np.array( [1,2],[3,4] )
a
a.ndim
a.dtype

TypeError: data type not understood

In [18]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
l=range(5)
l

range(0, 5)

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.arange(1,5,2)

array([1, 3])

In [28]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
np.array([1,2],[3,4])
a

TypeError: data type not understood

In [34]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,21))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


In [35]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [36]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [37]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
x.min

<function ndarray.min>

In [43]:
x.min()

0

In [44]:
x.max()

11

In [45]:
x.sum()

66

In [49]:
x = np.arange(12).reshape((3,4))

x.sum(axis=0)

array([12, 15, 18, 21])

In [47]:
x.sum(axis=1)

array([ 6, 22, 38])

In [50]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
np.sqrt(a)

NameError: name 'a' is not defined

In [53]:
a=[1,2,3]
a[0:2]

[1, 2]

In [56]:
a=[1,2,3,4,5,6]
a[0]


1

In [57]:
a=[1,2,3,4,5,6]
a[1]

2

In [58]:
a=[1,2,3,4,5,6]
a[0:1]

[1]

In [59]:
a=[1,2,3,4,5,6]
a[0:2]

[1, 2]

In [60]:
a=[1,2,3,4,5,6]
a[0:3]

[1, 2, 3]

In [61]:
a=[1,2,3,4,5,6]
a[0:4]

[1, 2, 3, 4]

In [62]:
a=[1,2,3,4,5,6]
a[0:-0]

[]

In [63]:
a=[1,2,3,4,5,6]
a[0:-1]

[1, 2, 3, 4, 5]

In [64]:
a=[1,2,3,4,5,6]
a[0:-2]

[1, 2, 3, 4]

In [65]:
a=[1,2,3,4,5,6]
a[0:-3]

[1, 2, 3]

In [66]:
a

[1, 2, 3, 4, 5, 6]