In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(11,20)


array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
n=[6,7,8]
n

[6, 7, 8]

In [14]:
n[0:2]

[6, 7]

In [15]:
n[0:-1]

[6, 7]

In [16]:
a=np.array([1,2,3],[4,5,6],[7,8,9])
a

ValueError: only 2 non-keyword arguments accepted

In [24]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.array([ [1,2,3],[4,5,6],[7,8,9] ])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a=np.array([ [1,2,3],[4,5,6],[7,8,9] ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a[0,2]

3

In [27]:
a[1,2]

6

In [28]:
a[-1]

array([7, 8, 9])

In [29]:
a[1]

array([4, 5, 6])

In [30]:
a[0]

array([1, 2, 3])

In [33]:
a[-1,0:1]

array([7])

In [34]:
a=np.array([ [1,2,3],[4,5,6],[7,8,9] ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
for row in a:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [39]:
for cell in a.flat:
  print(cell)

1
2
3
4
5
6
7
8
9


In [42]:
a= np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [44]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [48]:
a= np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
np.aspilt((a,3))
a

AttributeError: module 'numpy' has no attribute 'aspilt'

In [54]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
b=a<4
b

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [57]:
a[b]

array([0, 1, 2, 3])

In [59]:
a[b]=-1
a

array([[-1, -1, -1, -1],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a=np.arange(0,9).reshape(2,2)
a

ValueError: cannot reshape array of size 9 into shape (2,2)